urls.py
# -*- coding: utf-8 -*-
import os

from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

urlpatterns = \
    patterns('',
             (r'^admin/', include(admin.site.urls)),
             (r'^/?$', 'gdzie_byl_kaziu.gjm.views.index'),
             (r'^pobierzdane/$',
              'gdzie_byl_kaziu.gjm.views.panel_info'),

             # dajaxice
             (r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX,
              include('dajaxice.urls')),
        )

if settings.MODE in ('LOCAL', 'DEVEL'):
    urlpatterns += \
        patterns('',
                 (r'^templates/static/(?P<path>.*)$',
                  'django.views.static.serve',
                  {'document_root':
                   os.path.join(os.path.dirname(__file__),
                                ('/home/michal/Projects/gdzie_byl_kaziu/'
                                 'templates/static'))}))

gjm/models.py
#-*- coding: utf-8 -*-
from django.db import models


class Banknot(models.Model):
    """
    TODO

    """
    numer_seryjny = models.CharField(max_length=9)
    nominal_banknotu = models.IntegerField()
    nr_hash = models.CharField(max_length=40,
                               blank=True)

    def __unicode__(self):
        """
        TODO

        """
        return self.numer_seryjny


class Lokalizacja(models.Model):
    """
    TODO

    """
    banknot = models.ForeignKey(Banknot)
    data_dodania = models.DateTimeField(auto_now_add=True)
    kod_pocztowy = models.CharField(max_length=6,
                                    blank=True)
    login_uzytkownika = models.CharField(max_length=30)
    notka = models.TextField(blank=True)
    km = models.IntegerField(default=0)
    dl_geogr = models.CharField(max_length=50,
                                default=0)
    szer_geogr = models.CharField(max_length=50,
                                  default=0)
    predkosc = models.FloatField(blank=True,
                                 editable=False,
                                 default=0)
    delta_punkt = models.FloatField(blank=True,
                                    editable=False,
                                    default=0)

    def __unicode__(self):
        """
        TODO

        """
        return u'Dł: %s, szer: %s' % (self.dl_geogr, self.szer_geogr)

    def _get_date_delta(self):
        """
        Returns time difference between two dates.

        """
        l = Lokalizacja.objects.filter(banknot=self.banknot).\
            filter(id__lte=self.id).order_by('id').reverse()[:2]
        if l.count() is None or l.count() == 1:
            return 0
        else:
            td = l[0].data_dodania - l[1].data_dodania
            return td

    def _get_coord(self):
        """
        TODO

        """
        try:
            szer_polkula = 'S'
            dl_polkula = 'W'
            if (self.szer_geogr > 0):
                szer_polkula = 'N'
            if (self.dl_geogr > 0):
                dl_polkula = 'E'
            dd_szer = self.szer_geogr.split('.')
            dd_dl = self.dl_geogr.split('.')
            min_szer = float('0.' + dd_szer[1]) * 60
            min_dl = float('0.' + dd_dl[1]) * 60
            sek_szer = (min_szer % 1) * 60
            sek_dl = (min_dl % 1) * 60

            return u'%s° %d\' %d\'\' %s, %s° %d\' %d\'\' %s' % \
                (dd_szer[0], min_szer, sek_szer, szer_polkula,
                 dd_dl[0], min_dl, sek_dl, dl_polkula)
        except:
            return False

    # rejestrowanie property dla modelu Lokalizacja
    delta = property(_get_date_delta)
    wspolrzedne = property(_get_coord)

gjm/forms.py
# -*- coding: utf-8 -*-
from django import forms


ER_INVALID_SN_TXT = ("Niepoprawny numer seryjny. Sprawdź czy numer składa "
                     "się z 2 liter i 7 cyfr Np: XY1234567")


class DodajBanknot(forms.Form):
    """
    TODO

    """
    invalid_SN_txt = ("Niepoprawny numer seryjny. Sprawdź czy numer składa "
                      "się z 2 liter i 7 cyfr Np: XY1234567")
    numer_seryjny = \
        forms.RegexField('[A-Za-z]{2}\d{7}',
                         help_text="Numer składa się z 2 liter i 7 cyfr.",
                         error_messages={"invalid": ER_INVALID_SN_TXT})

    nominal = forms.ChoiceField(choices=[('10', '10'),
                                         ('20', '20'),
                                         ('50', '50'),
                                         ('100', '100'),
                                         ('200', '200')])

    kod_pocztowy = \
        forms.RegexField('\d{2}-\d{3}',
                         help_text=("Kod pocztowy oddzielony znakiem '-'. "
                                    "Na przykład: 41-200, 00-950 itp. "),
                         label='Kod pocztowy',
                         error_messages={'invalid':
                                         'Poprawna wartość to np: 41-200'})

    notka = \
        forms.CharField(label="Notka",
                        help_text=("Jeśli masz ciekawą historię dotyczącą "
                                   "banknotu to tu jest jej miejsce."),
                        required=False,
                        widget=forms.Textarea(attrs={'rows': 2, 'cols': 17}))

    szer_geogr = forms.CharField(widget=forms.HiddenInput, required=False)
    dl_geogr = forms.CharField(widget=forms.HiddenInput, required=False)


class powiadom(forms.Form):
    """
    TODO

    """
    powiadomienie = \
        forms.CharField(label="Informacje dotyczące kodu pocztowego",
                        help_text=("Wpisz informację pomagającą szybciej "
                                   "zweryfikować kod pocztowy."),
                        widget=forms.Textarea(attrs={'rows': 3, 'cols': 5}),
                        required=False)


class DodajBanknotWspl(forms.Form):
    """
    TODO

    """
    numer_seryjny = \
        forms.RegexField('[A-Za-z]{2}\d{7}',
                         help_text="Numer składa się z 2 liter i 7 cyfr.",
                         error_messages={"invalid": ER_INVALID_SN_TXT})

    nominal = forms.ChoiceField(choices=[('10', u'10 zł'),
                                         ('20', u'20 zł'),
                                         ('50', u'50 zł'),
                                         ('100', u'100 zł'),
                                         ('200', u'200 zł')])

    notka = \
        forms.CharField(label="Notka",
                        help_text=("Jeśli masz ciekawą historię dotyczącą "
                                   "banknotu to tu jest jej miejsce."),
                        required=False,
                        widget=forms.Textarea(attrs={'rows': 2, 'cols': 17}))
    szer_geogr = forms.CharField(label="Szerokość geogr.")
    dl_geogr = forms.CharField(label="Długość geogr.")

templates/base.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
          "http://www.w3.org/TR/html4/strict.dtd">
{% load dajaxice_templatetags  %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/main.css" />
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/jquery.tooltip.css" />
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/jquery-ui-1.8.1.custom.css" />
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/jquery.jgrowl.css" />
    <!--Production js 1.4.2-->
    <script type="text/javascript" src="{{MEDIA_URL}}/jquery.min.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}/jquery-ui.compiled.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}/jquery.serialize.compiled.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}/json2.compiled.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}/jquery.cookie.compiled.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}/main.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}/kazimierz.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}/jquery.enumerable.compiled.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}/jquery.timers.compiled.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}/jquery.bgiframe.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}/jquery.dimensions.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}/jquery.tooltip.pack.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}/jquery.jgrowl_compressed.js"></script>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&language=pl"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}/jquery.dajax.core.js"></script>

    {% dajaxice_js_import %}
    <title>{% block title%} {% endblock %} - permanentna inwigilacja banknotów - Gdzie Był Kaziu?</title>
  </head>

  <body>
    <div id="wrapper">
      <div class="header">
      </div>

      <div id="menu">
	    <div id="left">
	      <ul class="blue">
	        <li><a href="/"><span>Strona główna</span></a></li>
	      </ul>
	    </div>
      </div>
      <div id="clear"></div>

      <div id="content">
	    <div id="messages">
	      {{ request.META }}
	    </div>
	    {% block content %}
	    {% endblock %}

      </div>

      <div id="footer">
	{% block footer %}
	{% endblock %}
	<hr />
	Copyleft ALL WRONGS RESERVED <a href="http://michalklich.com">Michał Klich</a> 2013 |
	<a href="/">Strona główna</a> |
    <a href="https://twitter.com/GdzieBylKaziupl">twitter</a>
	<p>Wersja: Dajax'n'shit 0.666</p>
      </div>

      <a href="http://browsehappy.pl" class="badge">
	<img src="http://browsehappy.pl/2.png" alt="Nowoczesne przeglądarki" border="0" />
      </a>
      <a href="http://djangopony.com/" class="badge" title="Magic! Ponies! Django! Whee!"><img src="http://media.djangopony.com/img/small/badge.png" width="210" height="65" alt="pony powered" /></a>
    </div>
    {% block js%}

    {% endblock %}
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load custom_filters %}

{% block title %}
Strona główna
{% endblock %}

{% block content %}
<div id="container">
  <div id="left">
    <div id="wyszukiwanie">
      <div id="szukaj">
	<input type="text" id="wpisz_adres">
	<button type="button" id="szukaj_adres">Szukaj</button>
      </div>
      <div id="wyszukiwanie_message"></div>
      <button id="nowy_banknot">Nowy</button>
      <div id="howto">Kliknij na mapie aby dodać banknot</div>
      <div id="ostat_lokal_div">
	Ostatnie miejsca
	<select id="ostat_lokal">
	  <option>Wybierz</option>
	</select>
      </div>
    </div>
    <div id="mapa">
    </div>
    <div id="maps-form" class="hide">
      <form id="a-form" method="post">
	<p>
	  <label for="id_numer_seryjny">Numer seryjny:</label>
	  {{ form_maps.numer_seryjny }}
	</p>
	<p>
	  <label for="id_nominal">Nominał:</label>
	  {{ form_maps.nominal }}
	</p>
	<p>
	  <label for="id_notka">Info:</label>
	  {{ form_maps.notka }}
	</p>
	<p>
	  <label for="id_szer_geogr">Szerokość geograficzna:</label>
	  {{ form_maps.szer_geogr }}
	</p>
	<p>
	  <label for="id_dl_geogr">Długość geograficzna:</label>
	  {{ form_maps.dl_geogr }}
	</p>
	<button id="a-form-button"type="submit"
		value="Dodaj">Dodaj</button>
      </form>
    </div>
  </div>

  <div id="right">
    <div id="table_container">
    </div>
  </div>
  <div id="clear"></div>
  <div id="ajax_results">
    <table id="box-table-a">
      <thead>
	<tr>
	  <th>&sum; ilość użytkowników</th>
	  <th>&sum; wartość banknotów</th>
	  <th>&sum; ilość kilometrów</th>
	</tr>
      </thead>
      <tbody>
	<tr>
	  <td>0</td>
	  <td>0</td>
	  <td>0</td>
	</tr>
      </tbody>
    </table>
  </div>
</div>

<div id="szerokosc">
</div>
<div id="dlugosc">
</div>

{% endblock %}

{% block js %}

{% endblock %}

templates/panel.html
<table id="box-table-a">
  <thead>
    <tr>
      <th>&sum; ilość użytkowników</th>
      <th>&sum; wartość banknotów</th>
      <th>&sum; ilość kilometrów</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{users_total}}</td>
      <td>{{value_total}} zł</td>
      <td>{{km_total}} km</td>
    </tr>
  </tbody>
</table>